// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import { ShareItem } from '../models';

export interface ShareItemsControllerFindOneRequest {
  shareId: string;
}

export interface ShareItemsControllerRemoveRequest {
  shareId: string;
}

/**
 * no description
 */
export class ShareItemsApi extends BaseAPI {
  /**
   */
  shareItemsControllerFindAll(): Observable<Array<ShareItem>>;
  shareItemsControllerFindAll(opts?: OperationOpts): Observable<RawAjaxResponse<Array<ShareItem>>>;
  shareItemsControllerFindAll(opts?: OperationOpts): Observable<Array<ShareItem> | RawAjaxResponse<Array<ShareItem>>> {
    return this.request<Array<ShareItem>>(
      {
        url: '/api/share-items',
        method: 'GET',
      },
      opts?.responseOpts
    );
  }

  /**
   */
  shareItemsControllerFindOne({ shareId }: ShareItemsControllerFindOneRequest): Observable<ShareItem>;
  shareItemsControllerFindOne({ shareId }: ShareItemsControllerFindOneRequest, opts?: OperationOpts): Observable<RawAjaxResponse<ShareItem>>;
  shareItemsControllerFindOne({ shareId }: ShareItemsControllerFindOneRequest, opts?: OperationOpts): Observable<ShareItem | RawAjaxResponse<ShareItem>> {
    throwIfNullOrUndefined(shareId, 'shareId', 'shareItemsControllerFindOne');

    return this.request<ShareItem>(
      {
        url: '/api/share-items/{shareId}'.replace('{shareId}', encodeURI(shareId)),
        method: 'GET',
      },
      opts?.responseOpts
    );
  }

  /**
   */
  shareItemsControllerRemove({ shareId }: ShareItemsControllerRemoveRequest): Observable<ShareItem>;
  shareItemsControllerRemove({ shareId }: ShareItemsControllerRemoveRequest, opts?: OperationOpts): Observable<RawAjaxResponse<ShareItem>>;
  shareItemsControllerRemove({ shareId }: ShareItemsControllerRemoveRequest, opts?: OperationOpts): Observable<ShareItem | RawAjaxResponse<ShareItem>> {
    throwIfNullOrUndefined(shareId, 'shareId', 'shareItemsControllerRemove');

    return this.request<ShareItem>(
      {
        url: '/api/share-items/{shareId}'.replace('{shareId}', encodeURI(shareId)),
        method: 'DELETE',
      },
      opts?.responseOpts
    );
  }
}
