// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AuthorizeDto
 */
export interface AuthorizeDto {
  /**
   * @type {string}
   * @memberof AuthorizeDto
   */
  accessToken: string;
  /**
   * @type {string}
   * @memberof AuthorizeDto
   */
  idToken: string;
}
