// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreatePlaylistItemResponseDto
 */
export interface CreatePlaylistItemResponseDto {
  /**
   * @type {string}
   * @memberof CreatePlaylistItemResponseDto
   */
  mediaId: string;
  /**
   * @type {string}
   * @memberof CreatePlaylistItemResponseDto
   */
  userId: string;
  /**
   * @type {string}
   * @memberof CreatePlaylistItemResponseDto
   */
  playlistId: string;
  /**
   * @type {string}
   * @memberof CreatePlaylistItemResponseDto
   */
  _id: string;
}
