// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreateUserConnectionDto
 */
export interface CreateUserConnectionDto {
    /**
     * @type {object}
     * @memberof CreateUserConnectionDto
     */
    userId: object;
    /**
     * @type {object}
     * @memberof CreateUserConnectionDto
     */
    connectionId: object;
    /**
     * @type {string}
     * @memberof CreateUserConnectionDto
     */
    createdAt: string;
    /**
     * @type {string}
     * @memberof CreateUserConnectionDto
     */
    updatedDate: string;
}
