// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatePlaylistItemResponseDto, Playlist } from './';

/**
 * @export
 * @interface CreatePlaylistResponseDto
 */
export interface CreatePlaylistResponseDto {
  /**
   * @type {Playlist}
   * @memberof CreatePlaylistResponseDto
   */
  readonly playlist: Playlist;
  /**
   * @type {CreatePlaylistItemResponseDto}
   * @memberof CreatePlaylistResponseDto
   */
  playlistItems: CreatePlaylistItemResponseDto;
}
