// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface MediaItem
 */
export interface MediaItem {
  /**
   * @type {string}
   * @memberof MediaItem
   */
  readonly _id: string;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  readonly createdAt: string;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  readonly updatedDate?: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof MediaItem
   */
  createdBy: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof MediaItem
   */
  userId: string;
  /**
   * @type {boolean}
   * @memberof MediaItem
   */
  isPlayable: boolean;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  summary: string;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  description: string;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  title: string;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  uri: string;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  category: MediaItemCategoryEnum;
  /**
   * @type {string}
   * @memberof MediaItem
   */
  thumbnail: string;
}

/**
 * @export
 * @enum {string}
 */
export enum MediaItemCategoryEnum {
  Strength = 'strength',
  Flexibility = 'flexibility',
  Endurance = 'endurance',
}
