// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthorProfileDto, MediaCategoryType, TagKeyValue } from './';

/**
 * @export
 * @interface PlaylistItemResponseDto
 */
export interface PlaylistItemResponseDto {
  /**
   * @type {object}
   * @memberof PlaylistItemResponseDto
   */
  readonly _id: object;
  /**
   * @type {string}
   * @memberof PlaylistItemResponseDto
   */
  readonly createdAt: string;
  /**
   * @type {string}
   * @memberof PlaylistItemResponseDto
   */
  readonly updatedDate?: string;
  /**
   * @type {object}
   * @memberof PlaylistItemResponseDto
   */
  createdBy: object;
  /**
   * @type {object}
   * @memberof PlaylistItemResponseDto
   */
  userId: object;
  /**
   * @type {string}
   * @memberof PlaylistItemResponseDto
   */
  title: string;
  /**
   * @type {string}
   * @memberof PlaylistItemResponseDto
   */
  summary: string;
  /**
   * @type {string}
   * @memberof PlaylistItemResponseDto
   */
  description: string;
  /**
   * @type {string}
   * @memberof PlaylistItemResponseDto
   */
  uri: string;
  /**
   * @type {string}
   * @memberof PlaylistItemResponseDto
   */
  thumbnail: string;
  /**
   * @type {boolean}
   * @memberof PlaylistItemResponseDto
   */
  isPlayable?: boolean;
  /**
   * @type {MediaCategoryType}
   * @memberof PlaylistItemResponseDto
   */
  category?: MediaCategoryType;
  /**
   * @type {Array<TagKeyValue>}
   * @memberof PlaylistItemResponseDto
   */
  tags: Array<TagKeyValue> | null;
  /**
   * @type {object}
   * @memberof PlaylistItemResponseDto
   */
  playlistId: object;
  /**
   * @type {object}
   * @memberof PlaylistItemResponseDto
   */
  mediaId: object;
  /**
   * @type {number}
   * @memberof PlaylistItemResponseDto
   */
  sortIndex: number;
  /**
   * @type {AuthorProfileDto}
   * @memberof PlaylistItemResponseDto
   */
  authorProfile: AuthorProfileDto;
  /**
   * @type {number}
   * @memberof PlaylistItemResponseDto
   */
  shareCount: number;
  /**
   * @type {number}
   * @memberof PlaylistItemResponseDto
   */
  viewCount: number;
  /**
   * @type {number}
   * @memberof PlaylistItemResponseDto
   */
  likesCount: number;
}
