// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlaylistCategoryType, TagKeyValue } from './';

/**
 * @export
 * @interface Playlist
 */
export interface Playlist {
  /**
   * @type {object}
   * @memberof Playlist
   */
  readonly _id: object;
  /**
   * @type {string}
   * @memberof Playlist
   */
  readonly createdAt: string;
  /**
   * @type {string}
   * @memberof Playlist
   */
  readonly updatedDate?: string;
  /**
   * @type {object}
   * @memberof Playlist
   */
  createdBy: object;
  /**
   * @type {object}
   * @memberof Playlist
   */
  userId: object;
  /**
   * @type {string}
   * @memberof Playlist
   */
  title: string;
  /**
   * @type {string}
   * @memberof Playlist
   */
  description: string;
  /**
   * @type {string}
   * @memberof Playlist
   */
  imageSrc: string;
  /**
   * @type {Array<string>}
   * @memberof Playlist
   */
  mediaIds: Array<string> | null;
  /**
   * @type {PlaylistCategoryType}
   * @memberof Playlist
   */
  category?: PlaylistCategoryType;
  /**
   * @type {Array<TagKeyValue>}
   * @memberof Playlist
   */
  tags: Array<TagKeyValue> | null;
}
