// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BcRolesType,
    ProfileShareItem,
} from './';

/**
 * @export
 * @interface ProfileDto
 */
export interface ProfileDto {
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    _id: string;
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    createdBy: string;
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    imageSrc: string;
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    lastName: string;
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    email: string;
    /**
     * @type {BcRolesType}
     * @memberof ProfileDto
     */
    role: BcRolesType;
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    phoneNumber: string;
    /**
     * @type {string}
     * @memberof ProfileDto
     */
    username: string;
    /**
     * @type {Array<ProfileShareItem>}
     * @memberof ProfileDto
     */
    sharedItems: Array<ProfileShareItem>;
    /**
     * @type {number}
     * @memberof ProfileDto
     */
    sharedCount: number;
    /**
     * @type {number}
     * @memberof ProfileDto
     */
    sharesCount: number;
    /**
     * @type {number}
     * @memberof ProfileDto
     */
    likesCount: number;
}
