// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProfileShareItem
 */
export interface ProfileShareItem {
  /**
   * @type {string}
   * @memberof ProfileShareItem
   */
  createdAt: string;
  /**
   * @type {string}
   * @memberof ProfileShareItem
   */
  authorImage: string;
  /**
   * @type {string}
   * @memberof ProfileShareItem
   */
  authorName: string;
  /**
   * @type {string}
   * @memberof ProfileShareItem
   */
  author: string;
  /**
   * @type {object}
   * @memberof ProfileShareItem
   */
  authorId: object;
  /**
   * @type {string}
   * @memberof ProfileShareItem
   */
  imageSrc: string;
  /**
   * @type {object}
   * @memberof ProfileShareItem
   */
  playlistId: object;
  /**
   * @type {object}
   * @memberof ProfileShareItem
   */
  shareId: object;
  /**
   * @type {boolean}
   * @memberof ProfileShareItem
   */
  read: boolean;
  /**
   * @type {string}
   * @memberof ProfileShareItem
   */
  title: string;
}
