// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MediaItemResponseDto, PlaylistResponseDto } from './';

/**
 * @export
 * @interface ShareItemsResponseDto
 */
export interface ShareItemsResponseDto {
  /**
   * @type {MediaItemResponseDto}
   * @memberof ShareItemsResponseDto
   */
  mediaItems: MediaItemResponseDto;
  /**
   * @type {PlaylistResponseDto}
   * @memberof ShareItemsResponseDto
   */
  playlists: PlaylistResponseDto;
}
