// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    readonly _id?: string;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    readonly createdAt?: string;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    readonly updatedDate?: string;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    createdBy?: string;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    userId?: string;
}
