// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdatePlaylistDto
 */
export interface UpdatePlaylistDto {
  /**
   * @type {string}
   * @memberof UpdatePlaylistDto
   */
  readonly _id: string;
  /**
   * @type {string}
   * @memberof UpdatePlaylistDto
   */
  title: string;
  /**
   * @type {string}
   * @memberof UpdatePlaylistDto
   */
  description: string;
  /**
   * @type {string}
   * @memberof UpdatePlaylistDto
   */
  imageSrc: string;
  /**
   * @type {string}
   * @memberof UpdatePlaylistDto
   */
  category: string;
  /**
   * @type {Array<string>}
   * @memberof UpdatePlaylistDto
   */
  mediaIds?: Array<string>;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdatePlaylistDtoCategoryEnum {
  Paid = 'paid',
  Free = 'free',
}
