// tslint:disable
/**
 * Mediashare
 * Mediashare API
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserConnectionDto
 */
export interface UserConnectionDto {
    /**
     * @type {string}
     * @memberof UserConnectionDto
     */
    userId: string;
    /**
     * @type {string}
     * @memberof UserConnectionDto
     */
    connectionId: string;
    /**
     * @type {string}
     * @memberof UserConnectionDto
     */
    createdAt?: string;
    /**
     * @type {string}
     * @memberof UserConnectionDto
     */
    updatedDate?: string;
}
