// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ShareItem
 */
export interface ShareItem {
  /**
   *
   * @type {string}
   * @memberof ShareItem
   */
  _id: string;
  /**
   *
   * @type {Date}
   * @memberof ShareItem
   */
  readonly createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof ShareItem
   */
  readonly updatedDate?: Date;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof ShareItem
   */
  createdBy: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof ShareItem
   */
  readonly userId: string;
  /**
   *
   * @type {string}
   * @memberof ShareItem
   */
  playlistId?: string;
  /**
   *
   * @type {string}
   * @memberof ShareItem
   */
  mediaId?: string;
  /**
   *
   * @type {string}
   * @memberof ShareItem
   */
  title: string;
}

export function ShareItemFromJSON(json: any): ShareItem {
  return {
    _id: json['_id'],
    createdAt: new Date(json['createdAt']),
    updatedDate: !exists(json, 'updatedDate') ? undefined : new Date(json['updatedDate']),
    createdBy: json['createdBy'],
    userId: json['userId'],
    playlistId: !exists(json, 'playlistId') ? undefined : json['playlistId'],
    mediaId: !exists(json, 'mediaId') ? undefined : json['mediaId'],
    title: json['title'],
  };
}

export function ShareItemToJSON(value?: ShareItem): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    _id: value._id,
    createdBy: value.createdBy,
    playlistId: value.playlistId,
    mediaId: value.mediaId,
    title: value.title,
  };
}
