// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenDto
 */
export interface TokenDto  {
    /**
     * 
     * @type {string}
     * @memberof TokenDto
     */
    token: string;
}

export function TokenDtoFromJSON(json: any): TokenDto {
    return {
        'token': json['token'],
    };
}

export function TokenDtoToJSON(value?: TokenDto): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'token': value.token,
    };
}


