// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto  {
    /**
     * 
     * @type {Date}
     * @memberof UserDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserDto
     */
    readonly updatedDate?: Date;
    /**
     * Created by type is generated by the @CreateDto decorator
     * @type {string}
     * @memberof UserDto
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    readonly authId: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    roles: UserDtoRolesEnum;
}

export function UserDtoFromJSON(json: any): UserDto {
    return {
        'createdAt': new Date(json['createdAt']),
        'updatedDate': !exists(json, 'updatedDate') ? undefined : new Date(json['updatedDate']),
        'createdBy': json['createdBy'],
        'authId': json['authId'],
        'email': json['email'],
        'roles': json['roles'],
    };
}

export function UserDtoToJSON(value?: UserDto): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'createdAt': value.createdAt.toISOString(),
        'createdBy': value.createdBy,
        'email': value.email,
        'roles': value.roles,
    };
}

/**
* @export
* @enum {string}
*/
export enum UserDtoRolesEnum {
    Guest = 'guest',
    User = 'user',
    Admin = 'admin'
}


