default:
  image: node:16

stages:
  - build
  - triggers

build:
  stage: build
  script:
    - npm ci --force
    # npx nx print-affected --type=app --base=HEAD~1 prints the affected files via nx
    # make sure to put them in quotes, to prevent passing each character seperately to the node script
    # - npx nx affected --target=lint --parallel=3 --base=HEAD~1
    - node ./index.js "$(npx nx print-affected --type=app --base=HEAD~1)"
    - cat dynamic-gitlab-ci.yml
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
      - dynamic-gitlab-ci.yml

trigger:microservices:
  stage: triggers
  needs:
    - build
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml # this file is generated on runtime in the build stage
        job: build
    strategy: depend
