// tslint:disable
/**
 * Media Service
 * Media Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlaylistVisibilityType } from './';

/**
 * @export
 * @interface Playlist
 */
export interface Playlist {
  /**
   * @type {string}
   * @memberof Playlist
   */
  title: string;
  /**
   * @type {string}
   * @memberof Playlist
   */
  description: string;
  /**
   * @type {string}
   * @memberof Playlist
   */
  imageSrc: string;
  /**
   * @type {Array<string>}
   * @memberof Playlist
   */
  mediaIds: Array<string> | null;
  /**
   * @type {PlaylistVisibilityType}
   * @memberof Playlist
   */
  visibility?: PlaylistVisibilityType;
}
