// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    CreateMediaItemDto,
    MediaItem,
    UpdateMediaItemDto,
} from '../models';

export interface MediaItemControllerCreateRequest {
    createMediaItemDto: CreateMediaItemDto;
}

export interface MediaItemControllerFindOneRequest {
    id: string;
}

export interface MediaItemControllerRemoveRequest {
    id: string;
}

export interface MediaItemControllerShareRequest {
    id: string;
    userId: string;
}

export interface MediaItemControllerUpdateRequest {
    id: string;
    updateMediaItemDto: UpdateMediaItemDto;
}

/**
 * no description
 */
export class MediaItemsApi extends BaseAPI {

    /**
     */
    mediaItemControllerCreate({ createMediaItemDto }: MediaItemControllerCreateRequest): Observable<MediaItem>
    mediaItemControllerCreate({ createMediaItemDto }: MediaItemControllerCreateRequest, opts?: OperationOpts): Observable<RawAjaxResponse<MediaItem>>
    mediaItemControllerCreate({ createMediaItemDto }: MediaItemControllerCreateRequest, opts?: OperationOpts): Observable<MediaItem | RawAjaxResponse<MediaItem>> {
        throwIfNullOrUndefined(createMediaItemDto, 'createMediaItemDto', 'mediaItemControllerCreate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<MediaItem>({
            url: '/api/media-items',
            method: 'POST',
            headers,
            body: createMediaItemDto,
        }, opts?.responseOpts);
    };

    /**
     */
    mediaItemControllerFindAll(): Observable<Array<MediaItem>>
    mediaItemControllerFindAll(opts?: OperationOpts): Observable<RawAjaxResponse<Array<MediaItem>>>
    mediaItemControllerFindAll(opts?: OperationOpts): Observable<Array<MediaItem> | RawAjaxResponse<Array<MediaItem>>> {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<Array<MediaItem>>({
            url: '/api/media-items',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    mediaItemControllerFindOne({ id }: MediaItemControllerFindOneRequest): Observable<MediaItem>
    mediaItemControllerFindOne({ id }: MediaItemControllerFindOneRequest, opts?: OperationOpts): Observable<RawAjaxResponse<MediaItem>>
    mediaItemControllerFindOne({ id }: MediaItemControllerFindOneRequest, opts?: OperationOpts): Observable<MediaItem | RawAjaxResponse<MediaItem>> {
        throwIfNullOrUndefined(id, 'id', 'mediaItemControllerFindOne');

        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<MediaItem>({
            url: '/api/media-items/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    mediaItemControllerGetCategories(): Observable<void>
    mediaItemControllerGetCategories(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    mediaItemControllerGetCategories(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        return this.request<void>({
            url: '/api/media-items/categories',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    mediaItemControllerRemove({ id }: MediaItemControllerRemoveRequest): Observable<void>
    mediaItemControllerRemove({ id }: MediaItemControllerRemoveRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    mediaItemControllerRemove({ id }: MediaItemControllerRemoveRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'mediaItemControllerRemove');

        return this.request<void>({
            url: '/api/media-items/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
        }, opts?.responseOpts);
    };

    /**
     */
    mediaItemControllerShare({ id, userId }: MediaItemControllerShareRequest): Observable<MediaItem>
    mediaItemControllerShare({ id, userId }: MediaItemControllerShareRequest, opts?: OperationOpts): Observable<RawAjaxResponse<MediaItem>>
    mediaItemControllerShare({ id, userId }: MediaItemControllerShareRequest, opts?: OperationOpts): Observable<MediaItem | RawAjaxResponse<MediaItem>> {
        throwIfNullOrUndefined(id, 'id', 'mediaItemControllerShare');
        throwIfNullOrUndefined(userId, 'userId', 'mediaItemControllerShare');

        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<MediaItem>({
            url: '/api/media-items/{id}/share/{userId}'.replace('{id}', encodeURI(id)).replace('{userId}', encodeURI(userId)),
            method: 'POST',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    mediaItemControllerUpdate({ id, updateMediaItemDto }: MediaItemControllerUpdateRequest): Observable<MediaItem>
    mediaItemControllerUpdate({ id, updateMediaItemDto }: MediaItemControllerUpdateRequest, opts?: OperationOpts): Observable<RawAjaxResponse<MediaItem>>
    mediaItemControllerUpdate({ id, updateMediaItemDto }: MediaItemControllerUpdateRequest, opts?: OperationOpts): Observable<MediaItem | RawAjaxResponse<MediaItem>> {
        throwIfNullOrUndefined(id, 'id', 'mediaItemControllerUpdate');
        throwIfNullOrUndefined(updateMediaItemDto, 'updateMediaItemDto', 'mediaItemControllerUpdate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<MediaItem>({
            url: '/api/media-items/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: updateMediaItemDto,
        }, opts?.responseOpts);
    };

}
