// tslint:disable
/**
 *
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import { LoginDto, MediaItemDto, ShareItem, TokenDto, UserDto } from '../models';

export interface UserControllerAuthorizeRequest {
  id: string;
  tokenDto: TokenDto;
}

export interface UserControllerLoginRequest {
  loginDto: LoginDto;
}

/**
 * no description
 */
export class UserApi extends BaseAPI {
  /**
   */
  userControllerAuthorize({ id, tokenDto }: UserControllerAuthorizeRequest): Observable<void>;
  userControllerAuthorize(
    { id, tokenDto }: UserControllerAuthorizeRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  userControllerAuthorize(
    { id, tokenDto }: UserControllerAuthorizeRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(id, 'id', 'userControllerAuthorize');
    throwIfNullOrUndefined(tokenDto, 'tokenDto', 'userControllerAuthorize');

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/user/authorize'.replace('{:id}', encodeURI(id)),
        method: 'POST',
        headers,
        body: tokenDto,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  userControllerGetMediaItems(): Observable<UserDto>;
  userControllerGetMediaItems(opts?: OperationOpts): Observable<RawAjaxResponse<UserDto>>;
  userControllerGetMediaItems(opts?: OperationOpts): Observable<UserDto | RawAjaxResponse<UserDto>> {
    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<UserDto>(
      {
        url: '/api/user/media-items',
        method: 'GET',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  userControllerGetMyShareItems(): Observable<Array<ShareItem>>;
  userControllerGetMyShareItems(opts?: OperationOpts): Observable<RawAjaxResponse<Array<ShareItem>>>;
  userControllerGetMyShareItems(
    opts?: OperationOpts
  ): Observable<Array<ShareItem> | RawAjaxResponse<Array<ShareItem>>> {
    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<Array<ShareItem>>(
      {
        url: '/api/user/playlist/shared',
        method: 'GET',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  userControllerGetPlaylists(): Observable<UserDto>;
  userControllerGetPlaylists(opts?: OperationOpts): Observable<RawAjaxResponse<UserDto>>;
  userControllerGetPlaylists(opts?: OperationOpts): Observable<UserDto | RawAjaxResponse<UserDto>> {
    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<UserDto>(
      {
        url: '/api/user/playlists',
        method: 'GET',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  userControllerGetSharedMediaItems(): Observable<Array<MediaItemDto>>;
  userControllerGetSharedMediaItems(opts?: OperationOpts): Observable<RawAjaxResponse<Array<MediaItemDto>>>;
  userControllerGetSharedMediaItems(
    opts?: OperationOpts
  ): Observable<Array<MediaItemDto> | RawAjaxResponse<Array<MediaItemDto>>> {
    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<Array<MediaItemDto>>(
      {
        url: '/api/user/media-items/shared',
        method: 'GET',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  userControllerGetUser(): Observable<UserDto>;
  userControllerGetUser(opts?: OperationOpts): Observable<RawAjaxResponse<UserDto>>;
  userControllerGetUser(opts?: OperationOpts): Observable<UserDto | RawAjaxResponse<UserDto>> {
    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<UserDto>(
      {
        url: '/api/user',
        method: 'GET',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  userControllerLogin({ loginDto }: UserControllerLoginRequest): Observable<void>;
  userControllerLogin(
    { loginDto }: UserControllerLoginRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  userControllerLogin(
    { loginDto }: UserControllerLoginRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(loginDto, 'loginDto', 'userControllerLogin');

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/user/login',
        method: 'POST',
        headers,
        body: loginDto,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  userControllerLogout(): Observable<void>;
  userControllerLogout(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>;
  userControllerLogout(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
    return this.request<void>(
      {
        url: '/api/user/logout',
        method: 'POST',
      },
      opts?.responseOpts
    );
  }
}
