// tslint:disable
/**
 * User Service
 * User Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InviteDto
 */
export interface InviteDto {
  /**
   * @type {string}
   * @memberof InviteDto
   */
  email: string;
  /**
   * @type {string}
   * @memberof InviteDto
   */
  username: string;
}
