import { BcBaseInterface, IdType } from '@core-lib';
import { ApiObjectId, ApiPastDate } from '@mediashare/shared';
import { ApiProperty } from '@nestjs/swagger';
import { ObjectId } from 'bson';
import { ObjectIdColumn, Entity, CreateDateColumn, UpdateDateColumn, Column, PrimaryGeneratedColumn } from 'typeorm';

export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T[P] extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial<U>>
    : DeepPartial<T[P]> | T[P];
};

export abstract class BcBaseEntity<M> implements BcBaseInterface {
  @ObjectIdColumn()
  _id: ObjectId | string;

  constructor(model?: Partial<M>) {
    Object.assign(this, model);
  }
}

@Entity()
export class BcEntity implements BcBaseInterface {
  @ObjectIdColumn()
  @ApiObjectId({ readOnly: true })
  _id: ObjectId;

  @CreateDateColumn()
  @ApiProperty({ readOnly: true, type: Date })
  readonly createdAt?: Date;

  @UpdateDateColumn()
  @ApiPastDate({ readOnly: true, type: Date, required: false })
  readonly updatedDate?: Date;

  @Column()
  @ApiObjectId({
    description: 'Created by type is generated by the @CreateDto decorator'
  })
  readonly createdBy?: Readonly<ObjectId>;

  @Column()
  @ApiObjectId({
    description: 'Created by type is generated by the @CreateDto decorator'
  })
  userId?: ObjectId;
}
