/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsMobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id: 'us-west-2:22b996be-21de-48d0-8a8c-6cb55913d987',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_NIibhhG4d',
  aws_user_pools_web_client_id: '74efu0ifjdncifi8tksoiducu9',
  oauth: {},
  aws_cognito_login_mechanism: ['PREFERRED_USERNAME'],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_user_files_s3_bucket: 'mediashare0079445c24114369af875159b71aee1c04439-dev',
  aws_user_files_s3_bucket_region: 'us-west-2',
};

export default awsMobile;
