// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
  CreatePlaylistDto,
  CreatePlaylistResponseDto,
  PlaylistResponseDto,
  ShareItem,
  UpdatePlaylistDto,
} from '../models';

export interface PlaylistControllerCreateRequest {
  createPlaylistDto: CreatePlaylistDto;
}

export interface PlaylistControllerFindOneRequest {
  playlistId: string;
}

export interface PlaylistControllerRemoveRequest {
  playlistId: string;
}

export interface PlaylistControllerShareRequest {
  playlistId: string;
  userId: string;
}

export interface PlaylistControllerUpdateRequest {
  playlistId: string;
  updatePlaylistDto: UpdatePlaylistDto;
}

/**
 * no description
 */
export class PlaylistsApi extends BaseAPI {
  /**
   */
  playlistControllerCreate({
    createPlaylistDto,
  }: PlaylistControllerCreateRequest): Observable<CreatePlaylistResponseDto>;
  playlistControllerCreate(
    { createPlaylistDto }: PlaylistControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<CreatePlaylistResponseDto>>;
  playlistControllerCreate(
    { createPlaylistDto }: PlaylistControllerCreateRequest,
    opts?: OperationOpts
  ): Observable<CreatePlaylistResponseDto | RawAjaxResponse<CreatePlaylistResponseDto>> {
    throwIfNullOrUndefined(createPlaylistDto, 'createPlaylistDto', 'playlistControllerCreate');

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<CreatePlaylistResponseDto>(
      {
        url: '/api/playlists',
        method: 'POST',
        headers,
        body: createPlaylistDto,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  playlistControllerFindOne({ playlistId }: PlaylistControllerFindOneRequest): Observable<PlaylistResponseDto>;
  playlistControllerFindOne(
    { playlistId }: PlaylistControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<PlaylistResponseDto>>;
  playlistControllerFindOne(
    { playlistId }: PlaylistControllerFindOneRequest,
    opts?: OperationOpts
  ): Observable<PlaylistResponseDto | RawAjaxResponse<PlaylistResponseDto>> {
    throwIfNullOrUndefined(playlistId, 'playlistId', 'playlistControllerFindOne');

    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<PlaylistResponseDto>(
      {
        url: '/api/playlists'.replace('{playlistId}', encodeURI(playlistId)),
        method: 'GET',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  playlistControllerGetCategories(): Observable<void>;
  playlistControllerGetCategories(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>;
  playlistControllerGetCategories(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
    return this.request<void>(
      {
        url: '/api/playlists/categories',
        method: 'GET',
      },
      opts?.responseOpts
    );
  }

  /**
   */
  playlistControllerRemove({ playlistId }: PlaylistControllerRemoveRequest): Observable<void>;
  playlistControllerRemove(
    { playlistId }: PlaylistControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  playlistControllerRemove(
    { playlistId }: PlaylistControllerRemoveRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(playlistId, 'playlistId', 'playlistControllerRemove');

    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<void>(
      {
        url: '/api/playlists/{playlistId}'.replace('{playlistId}', encodeURI(playlistId)),
        method: 'DELETE',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  playlistControllerShare({ playlistId, userId }: PlaylistControllerShareRequest): Observable<Array<ShareItem>>;
  playlistControllerShare(
    { playlistId, userId }: PlaylistControllerShareRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<Array<ShareItem>>>;
  playlistControllerShare(
    { playlistId, userId }: PlaylistControllerShareRequest,
    opts?: OperationOpts
  ): Observable<Array<ShareItem> | RawAjaxResponse<Array<ShareItem>>> {
    throwIfNullOrUndefined(playlistId, 'playlistId', 'playlistControllerShare');
    throwIfNullOrUndefined(userId, 'userId', 'playlistControllerShare');

    const headers: HttpHeaders = {
      ...(this.configuration.username != null && this.configuration.password != null
        ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` }
        : undefined),
    };

    return this.request<Array<ShareItem>>(
      {
        url: '/api/playlists/{playlistId}'
          .replace('{playlistId}', encodeURI(playlistId))
          .replace('{userId}', encodeURI(userId)),
        method: 'POST',
        headers,
      },
      opts?.responseOpts
    );
  }

  /**
   */
  playlistControllerUpdate({ playlistId, updatePlaylistDto }: PlaylistControllerUpdateRequest): Observable<void>;
  playlistControllerUpdate(
    { playlistId, updatePlaylistDto }: PlaylistControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>>;
  playlistControllerUpdate(
    { playlistId, updatePlaylistDto }: PlaylistControllerUpdateRequest,
    opts?: OperationOpts
  ): Observable<void | RawAjaxResponse<void>> {
    throwIfNullOrUndefined(playlistId, 'playlistId', 'playlistControllerUpdate');
    throwIfNullOrUndefined(updatePlaylistDto, 'updatePlaylistDto', 'playlistControllerUpdate');

    const headers: HttpHeaders = {
      'Content-Type': 'application/json',
    };

    return this.request<void>(
      {
        url: '/api/playlists/{playlistId}'.replace('{playlistId}', encodeURI(playlistId)),
        method: 'PUT',
        headers,
        body: updatePlaylistDto,
      },
      opts?.responseOpts
    );
  }
}
