/* tslint:disable */
/* eslint-disable */
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Playlist } from './playlist';

/**
 *
 * @export
 * @interface CreatePlaylistResponseDto
 */
export interface CreatePlaylistResponseDto {
  /**
   *
   * @type {Playlist}
   * @memberof CreatePlaylistResponseDto
   */
  playlist: Playlist;
  /**
   *
   * @type {Array<string>}
   * @memberof CreatePlaylistResponseDto
   */
  playlistItems: Array<string>;
}
