/* tslint:disable */
/* eslint-disable */
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MediaItem } from './media-item';
import { Playlist } from './playlist';

/**
 *
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
  /**
   *
   * @type {string}
   * @memberof LoginResponseDto
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof LoginResponseDto
   */
  updatedDate?: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof LoginResponseDto
   */
  createdBy: string;
  /**
   *
   * @type {string}
   * @memberof LoginResponseDto
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof LoginResponseDto
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof LoginResponseDto
   */
  _id: string;
  /**
   *
   * @type {Array<MediaItem>}
   * @memberof LoginResponseDto
   */
  sharedMediaItems: Array<MediaItem>;
  /**
   *
   * @type {Array<Playlist>}
   * @memberof LoginResponseDto
   */
  sharedPlaylists: Array<Playlist>;
  /**
   *
   * @type {Array<MediaItem>}
   * @memberof LoginResponseDto
   */
  mediaItems: Array<MediaItem>;
  /**
   *
   * @type {Array<Playlist>}
   * @memberof LoginResponseDto
   */
  playlists: Array<Playlist>;
}
