/* tslint:disable */
/* eslint-disable */
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Playlist
 */
export interface Playlist {
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  _id: string;
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  updatedDate?: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof Playlist
   */
  createdBy: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof Playlist
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  title: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Playlist
   */
  mediaIds: Array<string>;
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  category: PlaylistCategoryEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PlaylistCategoryEnum {
  Rehab = 'rehab',
  Builder = 'builder',
  Warmup = 'warmup',
}
