/* tslint:disable */
/* eslint-disable */
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlaylistItemResponseDto } from './playlist-item-response-dto';

/**
 *
 * @export
 * @interface PlaylistResponseDto
 */
export interface PlaylistResponseDto {
  /**
   *
   * @type {string}
   * @memberof PlaylistResponseDto
   */
  _id: string;
  /**
   * Playlist response DTO
   * @type {PlaylistItemResponseDto}
   * @memberof PlaylistResponseDto
   */
  playlist_media_items_for_user: PlaylistItemResponseDto;
}
