/* tslint:disable */
/* eslint-disable */

/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
  /**
   *
   * @type {string}
   * @memberof UpdateUserDto
   */
  _id?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserDto
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserDto
   */
  updatedDate?: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof UpdateUserDto
   */
  createdBy?: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof UpdateUserDto
   */
  userId?: string;
}
