// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateMediaItemDto
 */
export interface UpdateMediaItemDto {
  /**
   * @type {object}
   * @memberof UpdateMediaItemDto
   */
  _id?: object;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  readonly createdAt?: string;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  readonly updatedDate?: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {object}
   * @memberof UpdateMediaItemDto
   */
  createdBy?: object;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {object}
   * @memberof UpdateMediaItemDto
   */
  userId?: object;
  /**
   * @type {boolean}
   * @memberof UpdateMediaItemDto
   */
  isPlayable?: boolean;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  summary?: string;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  description?: string;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  title?: string;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  displayFileName?: string;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  thumbnail?: string;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  uri?: string;
  /**
   * @type {string}
   * @memberof UpdateMediaItemDto
   */
  category?: UpdateMediaItemDtoCategoryEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateMediaItemDtoCategoryEnum {
  Strength = 'strength',
  Flexibility = 'flexibility',
  Endurance = 'endurance',
}
