/* tslint:disable */
/* eslint-disable */
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserDto
 */
export interface UserDto {
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  updatedDate?: string;
  /**
   * Created by type is generated by the @CreateDto decorator
   * @type {string}
   * @memberof UserDto
   */
  createdBy: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  authId: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  roles: UserDtoRolesEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UserDtoRolesEnum {
  Guest = 'guest',
  User = 'user',
  Admin = 'admin',
}
