// tslint:disable
/**
 * Mediashare
 * Media Share API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    username: string;
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    password: string;
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    lastName: string;
}
